import { v4 as uuid } from 'uuid'
import type { OpencodeEvent, QuestionInfo, StoredMessage, StoredMessagePart } from './protocol/types'
import type {
  ChatMessage,
  ContentBlock,
  PendingApproval,
  SessionResult,
  AskUserQuestion,
  TodoItem,
  FileDiff
} from '../../shared/types'
import { suggestOpencodeAllowRule } from './permission-compiler'

// Phase 6: the 5c tool-name normalization hack (OPENCODE_TOOL_NAME_MAP /
// normalizeOpencodeToolName, which rewrote the hosted-tools plugin names to the
// canonical `mcp__claude-ui*` forms) is RETIRED. tool_use blocks now carry the
// engine's RAW tool name (e.g. `bash`, `render_mermaid`); the renderer's
// kind-keyed registry (OpencodeEngineToolMap.kindOf) maps them to diagram/mockup/
// command/etc. and the engine-agnostic kind bodies render them.

// ── Part accumulator ─────────────────────────────────────────────────────────

/**
 * Token counts as reported by opencode's message.updated info.tokens.
 * All fields are optional — opencode may not populate all of them.
 */
export interface MessageTokens {
  input?: number
  output?: number
  /** Reasoning/thinking tokens (maps to a cache-write slot in billing) */
  reasoning?: number
  cache?: {
    read?: number
    write?: number
  }
}

/**
 * Live state for an in-progress assistant message.
 * Parts arrive as snapshots (upsert by part.id).
 */
export interface MessageAccumulator {
  messageId: string
  /** Role of the message (from `message.updated`'s `info.role`). Defaults to
   *  'assistant' until a `message.updated` records it. opencode emits
   *  `message.part.updated` for the USER's own text too — we must not render
   *  those as assistant bubbles. */
  role?: 'user' | 'assistant' | 'system'
  /** Latest cumulative cost snapshot for this message (`info.cost`). opencode
   *  re-emits `message.updated` multiple times per turn with a CUMULATIVE cost,
   *  so we store-not-add and sum across messages to get the turn total. */
  cost?: number
  /** Latest cumulative token snapshot for this message (`info.tokens`). Same
   *  cumulative semantics as cost — store, do not add. */
  tokens?: MessageTokens
  /** True when this accumulator belongs to a `task`-tool CHILD session (Phase 8d).
   *  Child messages share the parent's `accumulators` map (distinct messageIds),
   *  so the parent's metering loops (recordTurnUsage / sendMetering) must SKIP
   *  these — otherwise the child's tokens are silently attributed to the parent
   *  model. Phase 9a: child usage IS metered, but under the child's own model +
   *  childSessionId (not the parent). */
  isChild?: boolean
  /** The child's own session ID (populated on child message.updated events). Used by
   *  recordTurnUsage to attribute usage_events under the correct child session. */
  childSessionId?: string
  /** The model the child message was generated by (`info.providerID` + `info.modelID`).
   *  Only populated for child accumulators when both fields are present in the event. */
  model?: { providerID: string; modelID: string }
  /** Ordered part ids for block ordering. */
  partOrder: string[]
  /** Current snapshot per part.id */
  parts: Map<string, PartSnapshot>
}

export interface PartSnapshot {
  type: string
  text?: string
  toolName?: string
  callID?: string
  state?: ToolPartState
}

export interface ToolPartState {
  status?: string
  input?: Record<string, unknown>
  output?: string
  error?: string
  metadata?: Record<string, unknown>
  title?: string
}

// ── Mapper output types ───────────────────────────────────────────────────────

export type MapperOutput =
  | { kind: 'stream'; streamType: 'text' | 'thinking'; delta: string; messageId?: string }
  | { kind: 'message'; message: ChatMessage }
  | { kind: 'tool_result'; toolUseId: string; result: string; isError: boolean }
  | { kind: 'approval'; approval: PendingApproval }
  /** A pending permission was resolved server-side (M-OC2 — `permission.replied`).
   *  Fires for the reply we originated AND for every OTHER pending permission the
   *  vendor cascade-rejects (one reject rejects all) or cascade-approves (an
   *  `always` auto-approves matching ones). The consumer must retract the stale
   *  approval card for `requestId` — clicking it later would 404 forever. */
  | { kind: 'approval-resolved'; requestId: string }
  | { kind: 'result'; result: Pick<SessionResult, 'totalCostUsd' | 'durationMs' | 'result'> & { sessionId: string | null } }
  /** Emitted when cost changes OR when a token-snapshot context advance is detected (input+cacheRead
   *  increased on an assistant message). The latter fires even when cost=0 (free models), so that
   *  lastContextLength / buildStatusLine can reflect a real "context used %" instead of showing "–". */
  | { kind: 'cost_update'; totalCostUsd: number; messageId: string; tokens?: MessageTokens; engineCostUsd?: number }
  | { kind: 'error'; message: string }
  | { kind: 'auth-required'; vendorId: string; message: string }
  | { kind: 'subagent-stream'; toolUseId: string; streamType: 'text' | 'thinking'; delta: string }
  | { kind: 'subagent-message'; toolUseId: string; message: ChatMessage }
  | { kind: 'subagent-tool-result'; toolUseId: string; toolResultToolUseId: string; result: string; isError: boolean }
  | { kind: 'task-notification'; notification: import('../../shared/types').TaskNotification }
  | { kind: 'todos'; items: TodoItem[] }
  | { kind: 'ignore' }

// ── Mapper ────────────────────────────────────────────────────────────────────

/**
 * Pure function: map a single opencode SSE event to a MapperOutput.
 *
 * Stateful: `accumulators` is a Map keyed by messageId (the `msg_…` id from
 * message.updated / part.updated). The caller owns the map and passes it on
 * every call so this module stays pure and unit-testable.
 *
 * `childSessions` is a caller-owned Map<childSessionId, parentToolUseId> that
 * the mapper both reads (to route child events) and mutates (to register new
 * child sessions when a task tool part appears with state.metadata.sessionId).
 *
 * Routing logic (CRITICAL — order matters):
 *   1. eventSessionId === ownSessionId → own-session handler (existing switch)
 *      — also registers child sessions when a task tool part is seen.
 *   2. eventSessionId is a known child → child handler.
 *      A child's session.idle MUST be handled here and MUST NOT fall through to
 *      the own-session switch (where it would emit {kind:'result'} and end the
 *      parent turn early — the worst bug here).
 *   3. Unknown foreign session → ignore.
 */
export function mapEvent(
  ev: OpencodeEvent,
  ownSessionId: string,
  accumulators: Map<string, MessageAccumulator>,
  startTimeMs: number,
  totalCostUsd: { value: number },
  childSessions: Map<string, string> = new Map()
): MapperOutput {
  const props = ev.properties as Record<string, unknown>

  const eventSessionId = props.sessionID as string | undefined

  // ── Route: own session ───────────────────────────────────────────────────
  if (eventSessionId === ownSessionId) {
    return handleOwnEvent(ev, ownSessionId, accumulators, startTimeMs, totalCostUsd, childSessions)
  }

  // ── Route: known child session ────────────────────────────────────────────
  // CRITICAL: this branch must be reached BEFORE the own-session switch so that
  // a child's session.idle emits task-notification, NOT {kind:'result'}.
  if (eventSessionId && childSessions.has(eventSessionId)) {
    return handleChildEvent(ev, eventSessionId, accumulators, childSessions)
  }

  // ── Route: session.error with no sessionID → surface (don't drop) ─────────
  // The vendor marks `sessionID` optional on session.error and publishes plugin
  // crashes without one (plugin/index.ts). ClaudeUI always loads
  // claudeui-xeng-plugin, so a plugin fault would fall straight through to the
  // "ignore" fallback below and surface NOWHERE. Route it to a generic error so
  // the user at least sees that something failed. (A sessionID that IS present
  // but matches neither own nor a child belongs to another session and stays
  // ignored — only the sessionID-less global error is adopted here.)
  if (!eventSessionId && ev.type === 'session.error') {
    const err = props.error as { data?: Record<string, unknown> } | undefined
    const message =
      (err?.data?.message as string | undefined) ?? 'An opencode plugin or server error occurred'
    return { kind: 'error', message }
  }

  // ── Route: unknown foreign session → ignore ───────────────────────────────
  return { kind: 'ignore' }
}

/**
 * Handle events from the parent (own) session. This is the existing switch —
 * plus child-session registration when we see a task tool part.
 */
function handleOwnEvent(
  ev: OpencodeEvent,
  ownSessionId: string,
  accumulators: Map<string, MessageAccumulator>,
  startTimeMs: number,
  totalCostUsd: { value: number },
  childSessions: Map<string, string>
): MapperOutput {
  const props = ev.properties as Record<string, unknown>

  switch (ev.type) {
    case 'message.part.delta': {
      const messageId = props.messageID as string | undefined
      const field = props.field as string | undefined
      const delta = props.delta as string | undefined
      if (!delta || (field !== 'text' && field !== 'reasoning')) return { kind: 'ignore' }
      // peek at the accumulator to know the part type; default to text
      let streamType: 'text' | 'thinking' = 'text'
      if (messageId) {
        const acc = accumulators.get(messageId)
        if (acc) {
          const partId = props.partID as string | undefined
          if (partId) {
            const snap = acc.parts.get(partId)
            if (snap?.type === 'reasoning') streamType = 'thinking'
          }
        }
      }
      return { kind: 'stream', streamType, delta, messageId }
    }

    case 'message.part.updated': {
      const part = props.part as Record<string, unknown> | undefined
      if (!part) return { kind: 'ignore' }

      const partId = part.id as string | undefined
      const messageId = (part.messageID ?? part.messageId) as string | undefined
      if (!partId || !messageId) return { kind: 'ignore' }

      const acc = ensureAccumulator(accumulators, messageId)
      const isNew = !acc.parts.has(partId)
      if (isNew) acc.partOrder.push(partId)

      const partType = part.type as string
      const snap: PartSnapshot = { type: partType }

      if (partType === 'text' || partType === 'reasoning') {
        snap.text = (part.text as string) ?? ''
      } else if (partType === 'tool') {
        snap.toolName = part.tool as string
        snap.callID = part.callID as string
        const state = part.state as ToolPartState | undefined
        snap.state = state

        // Child-session registration: when a task tool part reports its child
        // sessionId, register it so future events from that child are routed to
        // handleChildEvent with the correct parent toolUseId (= callID).
        //
        // Ordering guarantee (verified vs opencode 1.17.9 task.ts):
        //   sessions.create(child)
        //   → ctx.metadata({ metadata: { sessionId } })   ← publishes this event (yield*)
        //   → background.start(runTask)                    ← runTask calls ops.prompt(child)
        //
        // ctx.metadata is yield*-ed (awaited synchronously in the Effect fiber) before
        // ops.prompt(child) is ever scheduled, so the registration event is emitted
        // and flushed to the single FIFO SSE stream BEFORE the child can emit any
        // transcript events (message.updated / message.part.updated / permission.asked).
        // No buffering is needed: child transcript events are always processed after
        // this registration is in place. (opencode/packages/opencode/src/tool/task.ts
        // lines 178–259 are the authoritative reference.)
        if (partType === 'tool' && (part.tool as string) === 'task') {
          const childSessionId = (state?.metadata as Record<string, unknown> | undefined)?.sessionId as string | undefined
          const callId = part.callID as string | undefined
          if (childSessionId && callId) {
            childSessions.set(childSessionId, callId)
          }
        }
      }
      acc.parts.set(partId, snap)

      // opencode emits part.updated for the USER's own text part too. The
      // user message is already rendered optimistically by the renderer, so
      // skip user-role messages here. `message.updated` (carrying info.role)
      // always arrives before the message's part.updated, so acc.role is set.
      if (acc.role === 'user') return { kind: 'ignore' }

      // Build the ChatMessage from current accumulator state
      const message = buildChatMessage(messageId, acc)

      return { kind: 'message', message }
    }

    case 'permission.asked': {
      const id = props.id as string | undefined
      const permission = props.permission as string | undefined
      const tool = props.tool as { messageID?: string; callID?: string } | undefined
      if (!id || !permission) return { kind: 'ignore' }

      // Offer an "always allow" suggestion (Claude addRules form) so the dialog
      // can persist a rule for this tool/pattern. patterns carries the matched
      // argument(s) (command / path / subagent type). See ADR-022 write-back.
      const patterns = props.patterns as string[] | undefined
      const suggestion = suggestOpencodeAllowRule(permission, patterns)

      // M-OC6: prefer the REAL tool-call input over the wire `metadata`. MCP
      // tools (claudeui_dispatch_agent + every bridged Claude MCP server) ask
      // with `metadata: {}`, leaving both the approval dialog and the ADR-023
      // auto-mode judge with zero context about what's being run. The tool part
      // carrying `state.input` is published (message.part.updated) before the
      // tool calls ctx.ask (verified vs vendor session/tools.ts — ctx.metadata
      // sets `input: args`), so it's already in the accumulator here. Fall back
      // to `metadata` (populated for built-in tools) then {}.
      const metadata = props.metadata as Record<string, unknown> | undefined
      const toolInput = findToolInput(accumulators, tool?.messageID, tool?.callID)
      const input =
        toolInput ?? (metadata && Object.keys(metadata).length > 0 ? metadata : {})

      const approval: PendingApproval = {
        requestId: id,
        toolUseId: tool?.callID,
        toolName: permission,
        input,
        // Carried through for the auto-mode ask-rule precedence check (G9) —
        // the classifier must never auto-approve what a user rule says to ask.
        ...(patterns && patterns.length > 0 ? { patterns } : {}),
        ...(suggestion ? { suggestions: [suggestion] } : {})
      }
      return { kind: 'approval', approval }
    }

    case 'permission.replied': {
      // M-OC2: a permission was resolved on the server. The vendor publishes
      // this for the reply we originated AND — on a `reject` — for EVERY other
      // pending permission in the session (cascade-reject), and on `always` for
      // matching pendings it auto-approves. Either way ClaudeUI's card for that
      // request is now stale (a later click 404s). Surface the requestId so the
      // consumer can retract it. Wire shape (vendor permission/index.ts +
      // event-reducer.test.ts): `{ sessionID, requestID }` — note `requestID`,
      // NOT `id` (which `permission.asked` uses).
      const requestId = props.requestID as string | undefined
      if (!requestId) return { kind: 'ignore' }
      return { kind: 'approval-resolved', requestId }
    }

    case 'session.idle': {
      const durationMs = Date.now() - startTimeMs
      return {
        kind: 'result',
        result: {
          totalCostUsd: totalCostUsd.value,
          durationMs,
          result: '',
          sessionId: ownSessionId
        }
      }
    }

    case 'session.error': {
      // Map opencode session.error → session:error or session:vendor-auth-required.
      // Wire shape (verified vs 1.17.9 /doc): properties.error =
      //   { name: 'ProviderAuthError'|'UnknownError'|…, data: { providerID?, message } }
      const err = props.error as { name?: string; data?: Record<string, unknown> } | undefined
      const name = err?.name
      const data = err?.data ?? {}
      if (name === 'ProviderAuthError') {
        const vendorId = data.providerID as string | undefined
        if (vendorId) {
          return {
            kind: 'auth-required',
            vendorId,
            message: (data.message as string | undefined) ?? 'Authentication required'
          }
        }
        // No providerID — fall back to generic error hint
        return {
          kind: 'error',
          message: 'Authentication required. Re-authorize in Settings › Vendors.'
        }
      }
      return { kind: 'error', message: (data.message as string | undefined) ?? 'An error occurred' }
    }

    case 'message.updated': {
      const info = props.info as Record<string, unknown> | undefined
      if (!info) return { kind: 'ignore' }

      const infoId = (info.id as string | undefined) ?? messageIdFromProps(props)
      if (!infoId) return { kind: 'ignore' }

      const acc = ensureAccumulator(accumulators, infoId)

      // Record role FIRST (before any early-return) so part.updated can gate
      // on it. opencode always emits message.updated before that message's
      // part.updated.
      const role = info.role as 'user' | 'assistant' | 'system' | undefined
      if (role === 'user' || role === 'assistant' || role === 'system') acc.role = role

      // info.tokens is a per-message CUMULATIVE snapshot (store, do not add).
      // Shape (from opencode 1.17.9 /doc): { input, output, reasoning, cache: { read, write } }
      // Capture the previous context dimension (input + cacheRead) BEFORE overwriting acc.tokens,
      // so we can detect a context-snapshot advance for free models (cost=0 never changes).
      const prevCtxLen = (acc.tokens?.input ?? 0) + (acc.tokens?.cache?.read ?? 0)
      const rawTokens = info.tokens as Record<string, unknown> | undefined
      if (rawTokens) {
        const cacheRaw = rawTokens.cache as Record<string, unknown> | undefined
        acc.tokens = {
          input: typeof rawTokens.input === 'number' ? rawTokens.input : undefined,
          output: typeof rawTokens.output === 'number' ? rawTokens.output : undefined,
          reasoning: typeof rawTokens.reasoning === 'number' ? rawTokens.reasoning : undefined,
          cache: cacheRaw
            ? {
                read: typeof cacheRaw.read === 'number' ? cacheRaw.read : undefined,
                write: typeof cacheRaw.write === 'number' ? cacheRaw.write : undefined
              }
            : undefined
        }
      }
      const newCtxLen = (acc.tokens?.input ?? 0) + (acc.tokens?.cache?.read ?? 0)
      // Gate on assistant role: only assistant messages carry a meaningful prompt size;
      // user/system token changes would corrupt lastContextLength in the session.
      const tokensChanged = newCtxLen !== prevCtxLen && acc.role === 'assistant'

      // info.cost is a per-message CUMULATIVE snapshot that re-emits multiple
      // times per turn. Store (not add) it on the accumulator, then sum across
      // all messages so the turn total is correct and never double-counts.
      let costChanged = false
      const cost = info.cost as number | undefined
      if (typeof cost === 'number') {
        const prev = acc.cost ?? 0
        acc.cost = cost
        if (cost !== prev) {
          costChanged = true
          totalCostUsd.value = sumAccumulatorCosts(accumulators)
        }
      }

      if (costChanged || tokensChanged) {
        return {
          kind: 'cost_update',
          totalCostUsd: totalCostUsd.value,
          messageId: infoId,
          tokens: acc.tokens,
          engineCostUsd: cost
        }
      }
      return { kind: 'ignore' }
    }

    case 'question.asked': {
      // The model is asking the user a structured question (opencode's analog of
      // Claude's AskUserQuestion tool). This is BLOCKING — the model suspends
      // until we reply or reject; an unanswered question hangs the turn.
      // Map to a PendingApproval with toolName:'AskUserQuestion' so the existing
      // AskUserQuestionBlock UI handles it engine-neutrally.
      const id = props.id as string | undefined
      const rawQuestions = props.questions as QuestionInfo[] | undefined
      const tool = props.tool as { messageID?: string; callID?: string } | undefined
      if (!id || !rawQuestions) return { kind: 'ignore' }
      return buildQuestionApproval(id, rawQuestions, tool?.callID)
    }

    case 'question.replied':
    case 'question.rejected':
      // Ack events — we originate the reply/reject from resolveApproval; the
      // server echo is redundant for a single client. Ignore silently.
      return { kind: 'ignore' }

    case 'command.executed':
      // Informational — the command's output has already streamed via the normal
      // message.updated / message.part.updated events. Completion is still marked
      // by session.idle, not this event. Nothing to do here. (Phase A note:
      // subtask command child-session events stay filtered until Phase D.)
      return { kind: 'ignore' }

    case 'todo.updated': {
      // opencode publishes todo.updated when the agent writes its TodoWrite tool.
      // Map to a {kind:'todos'} output so OpencodeSession can feed the floating widget.
      // Shape: { sessionID, todos: [{content, status, priority}] }
      const rawTodos = props.todos as Array<Record<string, unknown>> | undefined
      if (!Array.isArray(rawTodos)) return { kind: 'ignore' }
      const items: TodoItem[] = rawTodos.map((t) => ({
        content: t.content != null ? String(t.content) : '',
        // opencode adds 'cancelled'; TodoStatus now includes it — pass through
        status: (t.status as TodoItem['status']) ?? 'pending',
        activeForm: '' // opencode todowrite has no activeForm concept
      }))
      return { kind: 'todos', items }
    }

    default:
      return { kind: 'ignore' }
  }
}

/**
 * Handle events from a known child session (spawned by the parent's `task` tool).
 *
 * `toolUseId` = the parent task part's callID (from childSessions map).
 * The child's session.idle → task-notification (NEVER result — that would end
 * the parent turn early, the critical guard of this phase).
 */
function handleChildEvent(
  ev: OpencodeEvent,
  childSessionId: string,
  accumulators: Map<string, MessageAccumulator>,
  childSessions: Map<string, string>
): MapperOutput {
  const props = ev.properties as Record<string, unknown>
  const toolUseId = childSessions.get(childSessionId)!

  switch (ev.type) {
    case 'message.part.delta': {
      const messageId = props.messageID as string | undefined
      const field = props.field as string | undefined
      const delta = props.delta as string | undefined
      if (!delta || (field !== 'text' && field !== 'reasoning')) return { kind: 'ignore' }
      let streamType: 'text' | 'thinking' = 'text'
      if (messageId) {
        const acc = accumulators.get(messageId)
        if (acc) {
          const partId = props.partID as string | undefined
          if (partId) {
            const snap = acc.parts.get(partId)
            if (snap?.type === 'reasoning') streamType = 'thinking'
          }
        }
      }
      return { kind: 'subagent-stream', toolUseId, streamType, delta }
    }

    case 'message.part.updated': {
      const part = props.part as Record<string, unknown> | undefined
      if (!part) return { kind: 'ignore' }

      const partId = part.id as string | undefined
      const messageId = (part.messageID ?? part.messageId) as string | undefined
      if (!partId || !messageId) return { kind: 'ignore' }

      const acc = ensureAccumulator(accumulators, messageId)
      // Mark as a child accumulator so the parent's metering loops skip it
      // (otherwise the child's tokens are attributed to the parent model).
      acc.isChild = true
      const isNew = !acc.parts.has(partId)
      if (isNew) acc.partOrder.push(partId)

      const partType = part.type as string
      const snap: PartSnapshot = { type: partType }

      if (partType === 'text' || partType === 'reasoning') {
        snap.text = (part.text as string) ?? ''
      } else if (partType === 'tool') {
        snap.toolName = part.tool as string
        snap.callID = part.callID as string
        const state = part.state as ToolPartState | undefined
        snap.state = state
      }
      acc.parts.set(partId, snap)

      // Skip child user-role messages (the task prompt text) — mirrors the own path.
      // message.updated (with info.role) always precedes the message's part.updated.
      if (acc.role === 'user') return { kind: 'ignore' }

      const message = buildChatMessage(messageId, acc)
      return { kind: 'subagent-message', toolUseId, message }
    }

    case 'message.updated': {
      // Record role so part.updated can gate on it (same ordering contract as own path).
      // Accumulate tokens + cost for child metering (Phase 9a: recorded under the child's
      // own model + childSessionId in recordTurnUsage, not the parent's).
      // No cost_update emitted for child messages — the live MeteringSnapshot is the
      // parent turn's per-model meter; children are metered as their own usage_event.
      const info = props.info as Record<string, unknown> | undefined
      if (!info) return { kind: 'ignore' }

      const infoId = (info.id as string | undefined) ?? (props.messageID ?? props.messageId) as string | undefined
      if (!infoId) return { kind: 'ignore' }

      const acc = ensureAccumulator(accumulators, infoId)
      // Mark as a child accumulator so the parent's metering loops skip it.
      acc.isChild = true
      // Record which child session this accumulator belongs to (for usage attribution).
      acc.childSessionId = childSessionId

      const role = info.role as 'user' | 'assistant' | 'system' | undefined
      if (role === 'user' || role === 'assistant' || role === 'system') acc.role = role

      const rawTokens = info.tokens as Record<string, unknown> | undefined
      if (rawTokens) {
        const cacheRaw = rawTokens.cache as Record<string, unknown> | undefined
        acc.tokens = {
          input: typeof rawTokens.input === 'number' ? rawTokens.input : undefined,
          output: typeof rawTokens.output === 'number' ? rawTokens.output : undefined,
          reasoning: typeof rawTokens.reasoning === 'number' ? rawTokens.reasoning : undefined,
          cache: cacheRaw
            ? {
                read: typeof cacheRaw.read === 'number' ? cacheRaw.read : undefined,
                write: typeof cacheRaw.write === 'number' ? cacheRaw.write : undefined
              }
            : undefined
        }
      }

      // Phase 9a: capture cost for child messages (was deliberately omitted before).
      // Used by recordTurnUsage to emit a usage_event under the child's own model.
      const cost = info.cost as number | undefined
      if (typeof cost === 'number') acc.cost = cost

      // Capture the child's own model so recordTurnUsage can attribute the usage_event
      // correctly (child may run a different model than the parent).
      const providerID = info.providerID as string | undefined
      const modelID = info.modelID as string | undefined
      if (providerID && modelID) acc.model = { providerID, modelID }

      return { kind: 'ignore' }
    }

    case 'session.idle': {
      // CRITICAL GUARD: child session.idle → task-notification, NOT {kind:'result'}.
      // {kind:'result'} would flip isProcessing=false and end the parent turn early.
      // The child's toolUseId is deleted from childSessions in the dispatcher after
      // this notification is emitted (tidy cleanup).
      const notification: import('../../shared/types').TaskNotification = {
        taskId: childSessionId,
        toolUseId,
        status: 'completed',
        outputFile: '',
        summary: ''
      }
      return { kind: 'task-notification', notification }
    }

    case 'permission.asked': {
      // A child subagent hit an ask-gated tool. Surface it as a PendingApproval so
      // the user can unblock it — otherwise the child fiber stays suspended and the
      // synchronous parent turn hangs.
      //
      // Two deliberate differences from the own-session permission.asked case:
      //
      //   1. toolUseId = tool?.callID (THE CHILD TOOL'S own callID, NOT the parent
      //      task part's toolUseId stored in `toolUseId` above). The parent task
      //      toolUseId is already inside the rendered main assistant blocks, so
      //      FloatingApproval's unmatched-approval filter would immediately hide the
      //      card. The child tool's callID only appears inside the subagent blocks,
      //      so the card shows correctly.
      //
      //   2. `suggestions` (persist-rule) field is OMITTED. An "always allow" rule
      //      would be persisted to the shared Claude permission store → compiled into
      //      the parent's ruleset next spawn, but `deriveSubagentSessionPermission`
      //      (opencode 1.17.9) only copies parent *deny* rules to children — so the
      //      persisted allow would NOT stop the child re-asking. Including the
      //      suggestion would be misleading. Child approvals are once / session / deny
      //      only.
      const id = props.id as string | undefined
      const permission = props.permission as string | undefined
      const tool = props.tool as { messageID?: string; callID?: string } | undefined
      if (!id || !permission) return { kind: 'ignore' }

      const childPatterns = props.patterns as string[] | undefined
      const approval: import('../../shared/types').PendingApproval = {
        requestId: id,
        // Child tool's own callID — see note 1 above.
        toolUseId: tool?.callID,
        toolName: permission,
        input: (props.metadata as Record<string, unknown>) ?? {},
        // Carried for the auto-mode ask-rule precedence check (G9); a child ask
        // reaches handleAutoModeApproval on the same path as an own-session one.
        ...(childPatterns && childPatterns.length > 0 ? { patterns: childPatterns } : {})
        // No `suggestions` — see note 2 above.
      }
      return { kind: 'approval', approval }
    }

    case 'question.asked': {
      // A child subagent called the `question` tool. Surface it as a PendingApproval
      // so the user can answer it in the floating layer — otherwise the child fiber
      // stays suspended and the synchronous parent turn hangs.
      //
      // Key differences from the own-session question.asked case:
      //   1. toolUseId = tool?.callID (THE CHILD TOOL'S own callID, NOT the parent
      //      task part's toolUseId stored in `toolUseId` above). This keeps the
      //      card unmatched in FloatingApproval's filter — the child callID only
      //      appears inside subagent blocks, not the main assistant blocks.
      //   2. No `suggestions` field — question approvals never carry suggestions.
      // Everything else is shared via buildQuestionApproval.
      const id = props.id as string | undefined
      const rawQuestions = props.questions as QuestionInfo[] | undefined
      const tool = props.tool as { messageID?: string; callID?: string } | undefined
      if (!id || !rawQuestions) return { kind: 'ignore' }
      // Use tool?.callID (child question tool's callID), not the parent `toolUseId`.
      return buildQuestionApproval(id, rawQuestions, tool?.callID)
    }

    case 'session.error': {
      // Child session error → task-notification with status:'failed'.
      const notification: import('../../shared/types').TaskNotification = {
        taskId: childSessionId,
        toolUseId,
        status: 'failed',
        outputFile: '',
        summary: ''
      }
      return { kind: 'task-notification', notification }
    }

    default:
      return { kind: 'ignore' }
  }
}

/**
 * Build a {kind:'approval'} output for a question.asked event (own-session or child).
 *
 * Shared by both handleOwnEvent and handleChildEvent to keep the QuestionInfo[]→
 * AskUserQuestion[] mapping and PendingApproval construction in one place.
 *
 * @param id        The question request id (props.id)
 * @param rawQuestions The raw QuestionInfo array from the event
 * @param callID    The tool callID to use as toolUseId (own or child question tool's callID)
 */
function buildQuestionApproval(
  id: string,
  rawQuestions: QuestionInfo[],
  callID: string | undefined
): MapperOutput {
  const questions: AskUserQuestion[] = rawQuestions.map((q) => ({
    question: q.question,
    header: q.header,
    options: (q.options ?? []).map((o) => ({ label: o.label, description: o.description })),
    multiSelect: !!q.multiple
  }))
  const approval: PendingApproval = {
    requestId: id,
    toolUseId: callID,
    toolName: 'AskUserQuestion',
    input: { questions }
  }
  return { kind: 'approval', approval }
}

/** Get-or-create the accumulator for a messageId. */
function ensureAccumulator(
  accumulators: Map<string, MessageAccumulator>,
  messageId: string
): MessageAccumulator {
  let acc = accumulators.get(messageId)
  if (!acc) {
    acc = { messageId, partOrder: [], parts: new Map() }
    accumulators.set(messageId, acc)
  }
  return acc
}

/** Best-effort messageId from a message.updated event's properties. */
function messageIdFromProps(props: Record<string, unknown>): string | undefined {
  return (props.messageID ?? props.messageId) as string | undefined
}

/**
 * M-OC6: find the real input args of an in-flight tool call from the
 * accumulated tool part (state.input), matched by callID. Returns undefined
 * when no matching part carries a non-empty input — the caller then falls back
 * to the wire `metadata`. Checks the named message first, then scans all
 * accumulators (the permission event's `messageID` may be absent/mismatched).
 */
function findToolInput(
  accumulators: Map<string, MessageAccumulator>,
  messageId: string | undefined,
  callId: string | undefined
): Record<string, unknown> | undefined {
  if (!callId) return undefined
  const scan = (acc: MessageAccumulator | undefined): Record<string, unknown> | undefined => {
    if (!acc) return undefined
    for (const snap of acc.parts.values()) {
      if (snap.type === 'tool' && snap.callID === callId) {
        const input = snap.state?.input
        if (input && Object.keys(input).length > 0) return input
      }
    }
    return undefined
  }
  if (messageId) {
    const found = scan(accumulators.get(messageId))
    if (found) return found
  }
  for (const acc of accumulators.values()) {
    const found = scan(acc)
    if (found) return found
  }
  return undefined
}

/**
 * Sum the cumulative per-message cost snapshots into a turn total.
 *
 * Phase 9a: SKIP child accumulators (isChild). Now that child accumulators
 * capture `cost` for their own metering, failing to skip them here would inflate
 * the parent turn's totalCostUsd / cost_update (the own path calls this at the
 * cost_update path ~line 334 on every message.updated).
 */
function sumAccumulatorCosts(accumulators: Map<string, MessageAccumulator>): number {
  let total = 0
  for (const acc of accumulators.values()) {
    if (acc.isChild) continue
    total += acc.cost ?? 0
  }
  return total
}

/**
 * Build a ChatMessage from a MessageAccumulator snapshot.
 * Blocks are ordered by part insertion order; tool parts get tool_use blocks.
 */
export function buildChatMessage(messageId: string, acc: MessageAccumulator): ChatMessage {
  const content: ContentBlock[] = []

  for (const partId of acc.partOrder) {
    const snap = acc.parts.get(partId)
    if (!snap) continue

    if (snap.type === 'text') {
      content.push({ type: 'text', text: snap.text ?? '' })
    } else if (snap.type === 'reasoning') {
      content.push({ type: 'thinking', text: snap.text ?? '' })
    } else if (snap.type === 'tool') {
      const toolUseId = snap.callID ?? partId
      content.push({
        type: 'tool_use',
        toolUseId,
        // RAW opencode tool name — the renderer's OpencodeEngineToolMap classifies
        // it to a ToolKind (bash→command, render_mermaid→diagram, …). callID +
        // toolInput stay untouched (plugin arg names already match the bodies).
        toolName: snap.toolName ?? 'unknown',
        toolInput: snap.state?.input ?? {}
      })
    }
    // step-start/step-finish: ignored for now
  }

  return {
    id: messageId,
    role: acc.role ?? 'assistant',
    content,
    timestamp: Date.now()
  }
}

/**
 * Extract per-file unified diffs from a completed tool part's metadata, for the
 * file-mutation tools (apply_patch / edit). Shape-gated, not tool-name-gated —
 * bash's `{ output }` metadata (and anything else without `files`/`filediff`)
 * never matches, so callers don't need a hardcoded tool-name allowlist.
 *
 * Verified against vendor/opencode-src tag v1.17.15 (byte-identical to 1.17.14;
 * tool/{apply_patch,edit,write}.ts unchanged through pinned v1.18.9):
 *  - apply_patch result.metadata: `{ diff, files: [{ filePath, relativePath,
 *    type: 'add'|'update'|'delete'|'move', patch, additions, deletions,
 *    movePath }], diagnostics }`. The SAME shape also rides the
 *    `permission.asked` event, but that's a different message type — this
 *    helper only ever sees a completed/error part's `state.metadata`.
 *  - edit result.metadata: `{ diagnostics, diff, filediff: { file, patch,
 *    additions, deletions } }` — a SINGULAR object (always exactly one file),
 *    not an array. `filediff.file` is edit's own absolute `filePath` input
 *    echoed back; `input.filePath` is used only as a fallback if that's ever
 *    absent.
 *  - write result.metadata: `{ diagnostics, filepath, exists }` — NO diff at
 *    all. write's `permission.asked` event carries `{ filepath, diff }`, but
 *    that never reaches a completed part's `state.metadata`, so write
 *    intentionally yields no fileDiffs (falls through to the `undefined`
 *    return below — its generic/text rendering is unchanged).
 */
export function extractFileDiffs(
  metadata: Record<string, unknown> | undefined,
  input: Record<string, unknown> | undefined
): FileDiff[] | undefined {
  if (!metadata) return undefined

  // apply_patch shape: files[]
  if (Array.isArray(metadata.files)) {
    const diffs: FileDiff[] = []
    for (const raw of metadata.files as Array<Record<string, unknown>>) {
      const patch = raw.patch
      if (typeof patch !== 'string' || patch.length === 0) continue
      const path =
        (typeof raw.relativePath === 'string' && raw.relativePath) ||
        (typeof raw.filePath === 'string' ? raw.filePath : undefined)
      if (!path) continue
      const changeType =
        raw.type === 'add' || raw.type === 'update' || raw.type === 'delete' || raw.type === 'move'
          ? raw.type
          : undefined
      diffs.push({
        path,
        patch,
        additions: typeof raw.additions === 'number' ? raw.additions : undefined,
        deletions: typeof raw.deletions === 'number' ? raw.deletions : undefined,
        changeType
      })
    }
    return diffs.length > 0 ? diffs : undefined
  }

  // edit shape: filediff (singular)
  const filediff = metadata.filediff as Record<string, unknown> | undefined
  if (filediff && typeof filediff.patch === 'string' && filediff.patch.length > 0) {
    const path =
      (typeof filediff.file === 'string' && filediff.file) ||
      (typeof input?.filePath === 'string' ? input.filePath : undefined)
    if (!path) return undefined
    return [
      {
        path,
        patch: filediff.patch,
        additions: typeof filediff.additions === 'number' ? filediff.additions : undefined,
        deletions: typeof filediff.deletions === 'number' ? filediff.deletions : undefined,
        changeType: 'update'
      }
    ]
  }

  return undefined
}

/**
 * Check if a tool part snapshot represents a newly completed tool invocation.
 * Returns the tool result data, or null if not applicable.
 */
export function extractToolResult(
  _partId: string,
  snap: PartSnapshot
): { toolUseId: string; result: string; isError: boolean; fileDiffs?: FileDiff[] } | null {
  if (snap.type !== 'tool') return null
  const status = snap.state?.status
  if (status !== 'completed' && status !== 'error') return null
  const toolUseId = snap.callID ?? _partId
  const metadata = snap.state?.metadata as Record<string, unknown> | undefined
  // Error parts carry the failure text on state.error (e.g. a permission
  // denial's CorrectedError feedback) — prefer it so the reason is visible in
  // the tool card, live. Mirrors convertStoredMessage's history-path fallback.
  const stateError = snap.state?.error
  const rawOutput =
    status === 'error' && typeof stateError === 'string' && stateError.length > 0
      ? stateError
      : (snap.state?.output ?? metadata?.output)
  const result = rawOutput !== undefined ? String(rawOutput) : ''
  const fileDiffs = extractFileDiffs(metadata, snap.state?.input)
  return {
    toolUseId,
    result,
    isError: status === 'error',
    ...(fileDiffs ? { fileDiffs } : {})
  }
}

// Helper: generate a stable uuid for user messages
export function makeUserMessageId(): string {
  return uuid()
}

/**
 * Media types the engine-neutral `image` ContentBlock models (src/shared/types.ts).
 * Anything else is dropped rather than widened — the renderer builds
 * `data:<mediaType>;base64,…` URLs from these verbatim.
 */
const ATTACHMENT_IMAGE_MIME_TYPES = new Set(['image/jpeg', 'image/png', 'image/gif', 'image/webp'])

/**
 * Decode the base64 payload of a `data:<mime>;base64,<data>` URI, requiring the
 * header to match `mime` exactly. Returns null for anything else (`file://`
 * @-mention urls, missing comma, empty payload, mime/header mismatch, a
 * non-base64 data URI) — stored parts are untrusted input.
 */
function decodeBase64DataUri(url: string, mime: string): string | null {
  const comma = url.indexOf(',')
  if (comma === -1) return null
  if (url.slice(0, comma) !== `data:${mime};base64`) return null
  const data = url.slice(comma + 1)
  return data || null
}

/**
 * Map a stored `file` part to an attachment ContentBlock, or null when it is not
 * an inline user attachment. opencode uses `file` parts for two unrelated things:
 * real attachments (`data:` url, image/pdf mime — see OpencodeSession's file
 * parts) and @-mentioned files/directories (`file://` url, `text/plain` /
 * `application/x-directory` mime — vendor prompt.ts resolvePromptParts, already
 * expanded into synthetic text parts). Only the former is rehydrated.
 */
function storedFilePartToAttachment(part: StoredMessagePart): ContentBlock | null {
  const { mime, url, filename } = part
  if (typeof mime !== 'string' || typeof url !== 'string') return null
  const isImage = ATTACHMENT_IMAGE_MIME_TYPES.has(mime)
  if (!isImage && mime !== 'application/pdf') return null
  const base64Data = decodeBase64DataUri(url, mime)
  if (!base64Data) return null
  const fileName = filename ? { fileName: filename } : {}
  return isImage
    ? {
        type: 'image',
        mediaType: mime as 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp',
        base64Data,
        ...fileName
      }
    : { type: 'document', mediaType: 'application/pdf', base64Data, ...fileName }
}

/**
 * Convert a single stored opencode message (from GET /session/{id}/message) into
 * a `ChatMessage` for history replay.
 *
 * Mirrors `buildChatMessage`'s part→block mapping for parity with live turns:
 *   text      → { type:'text', text }
 *   reasoning → { type:'thinking', text }
 *   tool      → { type:'tool_use', toolUseId, toolName, toolInput }
 *              + { type:'tool_result', toolUseId, toolResult, isError } when completed/error
 *   file      → { type:'image'|'document', … } for inline USER attachments only
 *
 * Step-start, step-finish, agent, subtask, compaction, non-attachment file parts,
 * and any unknown part types are silently skipped.
 *
 * Returns null if the message has no displayable content (so the caller can skip it).
 */
export function convertStoredMessage(stored: StoredMessage): ChatMessage | null {
  const { info, parts } = stored
  if (!info?.id) return null

  const role = info.role ?? 'assistant'
  // Only user/assistant messages are renderable; skip system messages.
  if (role !== 'user' && role !== 'assistant') return null

  const content: ContentBlock[] = []
  // Attachments are hoisted ahead of the rest: ClaudeUI sends opencode
  // [text, ...fileParts] so they persist AFTER the prompt, while the live echo
  // (session-store.ts addUserMessage / OpencodeSession.buildUserContent) puts
  // them first. Replay must match the live order.
  const attachments: ContentBlock[] = []

  for (const part of (parts ?? []) as StoredMessagePart[]) {
    const type = part.type

    if (type === 'file') {
      if (role !== 'user') continue
      const block = storedFilePartToAttachment(part)
      if (block) attachments.push(block)
    } else if (type === 'text') {
      const text = part.text ?? ''
      if (text) content.push({ type: 'text', text })
    } else if (type === 'reasoning') {
      const text = part.text ?? ''
      if (text) content.push({ type: 'thinking', text })
    } else if (type === 'tool') {
      const toolUseId = part.callID ?? part.id ?? uuid()
      const toolName = part.tool ?? 'unknown'
      const input = (part.state?.input ?? {}) as Record<string, unknown>
      content.push({ type: 'tool_use', toolUseId, toolName, toolInput: input })

      // Add tool_result if the tool completed or errored.
      const status = part.state?.status
      if (status === 'completed' || status === 'error') {
        const rawOutput = part.state?.output ?? part.state?.error ?? ''
        const fileDiffs = extractFileDiffs(part.state?.metadata, input)
        content.push({
          type: 'tool_result',
          toolUseId,
          toolResult: rawOutput ?? '',
          isError: status === 'error',
          ...(fileDiffs ? { fileDiffs } : {})
        })
      }
    }
    // step-start, step-finish, agent, subtask, compaction → skip
  }

  if (attachments.length > 0) content.unshift(...attachments)

  // If there's no renderable content, skip this message entirely.
  if (content.length === 0) return null

  const timestamp = (info.time as { created?: number } | undefined)?.created ?? Date.now()
  return {
    id: info.id,
    role: role as 'user' | 'assistant',
    content,
    timestamp
  }
}

/**
 * Reconstruct accumulated ACTIVE (turn-processing) duration from opencode's
 * stored-message history (GET /session/{id}/message), for durability across
 * reloads. Mirrors Claude's transcript turn-span reconstruction (see
 * session-history.ts `computeTurnSpanDurationMs`) with the same semantic:
 * accumulated wall-clock time actively processing turns — idle time (waiting
 * on the user) is excluded, and both engines share this definition.
 *
 * A turn starts at a `role: 'user'` stored message (`info.time.created`) and
 * ends at the latest `time.completed` (fallback: `time.created`) among the
 * assistant messages that follow it, up to the next user message. Messages
 * are assumed to arrive in chronological order, as `listMessages` returns
 * them. Missing/non-finite timestamps are skipped for span math (a user
 * message with no parseable `created` drops that whole turn rather than
 * guessing a start); negative/NaN spans are clamped to 0.
 */
export function computeStoredDurationMs(storedMessages: StoredMessage[]): number {
  let totalMs = 0
  let turnStartMs: number | null = null
  let turnEndMs: number | null = null

  const finalizeTurn = (): void => {
    if (turnStartMs !== null && turnEndMs !== null) {
      const span = turnEndMs - turnStartMs
      if (Number.isFinite(span) && span > 0) totalMs += span
    }
    turnStartMs = null
    turnEndMs = null
  }

  for (const stored of storedMessages) {
    const info = stored.info
    if (!info) continue
    const time = info.time as { created?: number; completed?: number } | undefined

    if (info.role === 'user') {
      finalizeTurn()
      const created = time?.created
      turnStartMs = typeof created === 'number' && Number.isFinite(created) ? created : null
      continue
    }

    if (info.role !== 'assistant' || turnStartMs === null) continue
    const end = time?.completed ?? time?.created
    if (typeof end !== 'number' || !Number.isFinite(end)) continue
    if (turnEndMs === null || end > turnEndMs) turnEndMs = end
  }
  finalizeTurn()

  return totalMs
}
