/**
 * ClaudeUI pi approval-bridge extension — source constant.
 *
 * pi has no native permission system (see docs/protocol-pi/README.md
 * "Extensions" — verified in M0 against the real standalone binary). The
 * sanctioned mechanism is a ClaudeUI-owned extension loaded per-spawn with
 * `-e`, whose `tool_call` hook returns `{block: true, reason}` to prevent
 * execution, consulting a loopback HTTP endpoint (PiBridgeHost) for the
 * decision:
 *
 *   pi child (this extension) --POST /tool-call--> PiBridgeHost (main process)
 *                              <--{behavior:'allow'|'deny', ...}--
 *
 * This string is written verbatim to
 * `<os.tmpdir()>/claudeui-pi-bridge/<PI_BRIDGE_VERSION>/claudeui-bridge.ts`
 * by `writeBridgeExtension()` (PiBridgeHost.ts) and loaded via
 * `pi --mode rpc -e <path>`. Never written under `~/.pi/**` — that's user
 * space.
 *
 * CONSTRAINTS (do not violate when editing this string):
 *  - NO `import` statements. This file is compiled by pi's OWN jiti loader in
 *    a separate process — it is not part of ClaudeUI's tsconfig/bundle and
 *    has zero module-resolution surface (no node_modules relative to it, no
 *    path aliases). `export default function (pi) {}` is the entire contract
 *    pi needs; `fetch` and `process.env` are ambient globals in pi's runtime
 *    (verified — extensions.md's own `tool_result` example calls bare
 *    `fetch()` with no import).
 *  - Must be INERT (register nothing) when CLAUDEUI_PI_BRIDGE_URL/TOKEN are
 *    absent, so a user launching the pinned binary by hand (outside
 *    ClaudeUI) is never affected by this file existing on disk.
 *  - Fail CLOSED on every error path (network failure, non-2xx, bad JSON) —
 *    an unreachable ClaudeUI host must never silently allow a tool call
 *    through. Never include the URL or bearer token in a reason string (that
 *    text can end up in the model's context).
 *  - Bump PI_BRIDGE_VERSION whenever this string changes. The file on disk is
 *    write-if-absent and version-keyed by directory, so a stale copy from a
 *    previous ClaudeUI build never shadows an edit made here.
 *  - M3 ADDED a `resources_discover` handler (shared-skills directive) gated
 *    INDEPENDENTLY on its OWN env var (CLAUDEUI_PI_SKILL_DIRS) — a separate
 *    `if` block, not nested under the bridge URL/token check. Neither hook may
 *    gate on the other's env var: the skills env var alone must not activate
 *    tool_call, and the bridge URL/token alone must not activate
 *    resources_discover.
 */

export const PI_BRIDGE_VERSION = '2'

export const PI_BRIDGE_EXTENSION_SOURCE = `// AUTO-GENERATED by ClaudeUI (src/main/pi/pi-bridge-source.ts). Do not edit
// this file directly -- it is overwritten on the next ClaudeUI launch.
//
// ClaudeUI approval-bridge extension. Inert unless both CLAUDEUI_PI_BRIDGE_URL
// and CLAUDEUI_PI_BRIDGE_TOKEN are set in the environment (ClaudeUI sets both
// per-spawn; a user running this pinned pi binary by hand never sets them, so
// the extension registers nothing and is a complete no-op for them).
export default function (pi) {
  // Shared-skills discovery (M3): independently gated on its OWN env var --
  // registered (or not) BEFORE the bridge URL/token check below returns early,
  // so neither hook's presence depends on the other's env var. Absent means
  // this handler is never registered, so a user running the pinned binary by
  // hand (or a spawn with no skill dirs to contribute) is unaffected. The main
  // process computes the dir list (checking existence) and passes it via env;
  // this handler just splits the string -- no fs access here, keeps the
  // extension dumb.
  const skillDirsEnv = process.env.CLAUDEUI_PI_SKILL_DIRS;
  if (skillDirsEnv) {
    pi.on('resources_discover', () => {
      // Node's path.delimiter without importing node:path (see the
      // no-import constraint above) -- process is already an ambient global.
      var delimiter = process.platform === 'win32' ? ';' : ':';
      var skillPaths = skillDirsEnv.split(delimiter).filter(function (p) { return p.length > 0; });
      return { skillPaths: skillPaths };
    });
  }

  const bridgeUrl = process.env.CLAUDEUI_PI_BRIDGE_URL;
  const bridgeToken = process.env.CLAUDEUI_PI_BRIDGE_TOKEN;
  if (!bridgeUrl || !bridgeToken) return;

  pi.on('tool_call', async (event) => {
    try {
      const res = await fetch(bridgeUrl + '/tool-call', {
        method: 'POST',
        headers: {
          authorization: 'Bearer ' + bridgeToken,
          'content-type': 'application/json'
        },
        body: JSON.stringify({
          toolCallId: event.toolCallId,
          toolName: event.toolName,
          input: event.input
        })
      });

      if (!res.ok) {
        return { block: true, reason: 'ClaudeUI approval service unreachable (HTTP ' + res.status + ')' };
      }

      const decision = await res.json();

      if (decision && decision.behavior === 'allow') {
        if (decision.updatedInput && typeof decision.updatedInput === 'object') {
          // Documented allow-with-edits mechanism: mutate event.input IN PLACE
          // (reassigning event.input would not affect the actual tool call).
          for (const key of Object.keys(event.input)) delete event.input[key];
          Object.assign(event.input, decision.updatedInput);
        }
        return undefined;
      }

      return { block: true, reason: (decision && decision.reason) || 'Denied by ClaudeUI' };
    } catch (err) {
      // Network failure, timeout, or bad JSON -- fail CLOSED. Never surface
      // the bridge URL or token here.
      const errorClass = err && err.constructor && err.constructor.name ? err.constructor.name : 'Error';
      return { block: true, reason: 'ClaudeUI approval service unreachable (' + errorClass + ')' };
    }
  });

  // The user already chose to open/trust this folder in ClaudeUI -- the
  // desktop app itself is the trust boundary, not pi's own per-project
  // trust.json. remember:false deliberately does NOT persist this decision to
  // pi's trust store: trust is re-derived fresh from ClaudeUI's own state on
  // every launch, and since this handler only participates when
  // CLAUDEUI_PI_BRIDGE_URL/TOKEN are set (i.e. ClaudeUI itself spawned the
  // process -- see the early return above), a user running the SAME pinned
  // binary by hand still gets pi's own built-in trust prompt untouched.
  pi.on('project_trust', () => ({ trusted: 'yes', remember: false }));
}
`
