/**
 * ClaudeUI pi in-process subagent extension — source constant (M5b).
 *
 * A SECOND ClaudeUI-owned `-e` extension, separate from the approval bridge
 * (pi-bridge-source.ts). The bridge stays import-free BY CHOICE (smaller tamper
 * surface); this one genuinely NEEDS `node:child_process`/`node:fs`/`node:os`/
 * `node:path` to spawn child `pi` processes and manage per-agent temp prompt
 * files — verified safe: docs/protocol-pi/README.md "Extensions" ("Imports
 * work in -e extensions — node builtins AND relative imports resolve from an
 * arbitrary file path outside any package context").
 *
 * Ported from pi's OWN shipped reference implementation
 * (`vendor/pi-cli/examples/extensions/subagent/{index,agents}.ts`), cut down
 * to v1 scope per the M5b kickoff spec:
 *   - Agent discovery is USER-LEVEL ONLY (`~/.pi/agent/agents/*.md`, or
 *     `CLAUDEUI_PI_AGENTS_DIR` for tests/override) — the example's
 *     project-local `.pi/agents` + agentScope/confirmProjectAgents dance is
 *     explicitly OUT of v1 (see the example's README "Security Model" for why
 *     that one needs its own confirm-UI story before landing here).
 *   - No `chain` mode (sequential steps with a `{previous}` placeholder) — only
 *     single ({agent, task}) and parallel ({tasks: [...]})
 *   - No markdown-rendered TUI card (renderCall/renderResult) — this extension
 *     only powers the WIRE contract (`pi.registerTool().execute()`); rendering
 *     is the renderer's job via PiEngineToolMap's 'task' kind + TaskCard
 *     (engine-neutral, shared with cross-engine dispatch).
 *   - No frontmatter YAML library (no npm deps are available next to this
 *     tmp-written file — verified probe fact) — a minimal inline
 *     `---\n...\n---` splitter handles the flat string fields pi agent
 *     definitions actually use (name/description/model/tools).
 *
 * Whole extension gated on `process.env.CLAUDEUI_PI_SUBAGENTS === '1'`
 * (PiSession.doStart, mirroring every other capability-gated block in
 * pi-bridge-source.ts) — inert (returns immediately, registers nothing) for a
 * user running the pinned binary by hand. Within that gate, a SECOND
 * condition — zero `.md` agent definitions discovered — ALSO skips
 * registration entirely (no prompt pollution advertising a tool with no
 * agents to invoke).
 *
 * Written to `<os.tmpdir()>/claudeui-pi-subagent/<PI_SUBAGENT_VERSION>/
 * claudeui-subagent.ts` by `writeSubagentExtension()` (PiBridgeHost.ts) — the
 * SAME content-verify-on-every-call posture `writeBridgeExtension()` uses
 * (rewrite on any mismatch; write-if-absent alone would leave a preplant
 * window on a world-writable POSIX /tmp). Never written under `~/.pi/**`.
 *
 * SECURITY / TRUST MODEL (required reading before editing):
 *   - Children are spawned with NO `-e` flags of their own — recursion into
 *     another subagent tool, the approval bridge, or hosted tools is
 *     STRUCTURALLY absent, not policy-absent: a pi process with no `-e`
 *     extension loaded has no code path that could read
 *     CLAUDEUI_PI_BRIDGE_URL/TOKEN or any other CLAUDEUI_PI_* env var for
 *     anything (those names are meaningless to pi's own core), so inheriting
 *     them through the default spawn env merge is harmless — there's nothing
 *     in the child that would ever act on them.
 *   - The `subagent` tool call ITSELF still goes through the PARENT session's
 *     normal tool_call gate (piToolKind('subagent') -> 'task' in
 *     permission-engine.ts — ask in default mode, allow in full, deny in
 *     plan) exactly like `dispatch_agent`. Once past that gate, the CHILD
 *     process runs its agent-def toolset completely UNGATED — the same
 *     two-stage posture as the M4c cross-engine dispatch TARGET (gate once at
 *     the boundary, then trust the far side's own autonomy). This is safe
 *     ONLY because agent `.md` definitions are USER-authored files in a
 *     user-level directory the model cannot write to through this tool.
 *   - This file NEVER references CLAUDEUI_PI_BRIDGE_URL/TOKEN — it has no
 *     network call of its own (child stdout is read directly over a pipe,
 *     not proxied through PiBridgeHost) and must stay that way; a tripwire
 *     test in pi-subagent-source.test.ts asserts this.
 *
 * Bump PI_SUBAGENT_VERSION whenever this string changes (mirrors
 * PI_BRIDGE_VERSION's directory-keyed write-if-mismatched-only contract).
 */

export const PI_SUBAGENT_VERSION = '2'

export const PI_SUBAGENT_EXTENSION_SOURCE = `// AUTO-GENERATED by ClaudeUI (src/main/pi/pi-subagent-source.ts). Do not
// edit this file directly -- it is overwritten on the next ClaudeUI launch.
//
// ClaudeUI in-pi subagent extension. Inert unless CLAUDEUI_PI_SUBAGENTS=1 is
// set in the environment (ClaudeUI sets it per-spawn when capabilities.subagents
// is true; a user running this pinned pi binary by hand never sets it, so this
// extension registers nothing and is a complete no-op for them).
import { spawn } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

export default function (pi) {
  if (process.env.CLAUDEUI_PI_SUBAGENTS !== '1') return;

  var agentsDir = process.env.CLAUDEUI_PI_AGENTS_DIR || path.join(os.homedir(), '.pi', 'agent', 'agents');

  // ---- Minimal frontmatter parsing (no npm deps available next to this
  // tmp-written file -- only flat string fields are needed: name,
  // description, model?, tools?). ----
  function parseFrontmatter(content) {
    var m = /^---\\r?\\n([\\s\\S]*?)\\r?\\n---\\r?\\n?([\\s\\S]*)$/.exec(content);
    if (!m) return { frontmatter: {}, body: content };
    var frontmatter = {};
    var lines = m[1].split(/\\r?\\n/);
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      var idx = line.indexOf(':');
      if (idx === -1) continue;
      var key = line.slice(0, idx).trim();
      var value = line.slice(idx + 1).trim();
      if (value.length >= 2) {
        var first = value.charAt(0);
        var last = value.charAt(value.length - 1);
        if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
          value = value.slice(1, -1);
        }
      }
      if (key) frontmatter[key] = value;
    }
    return { frontmatter: frontmatter, body: (m[2] || '').trim() };
  }

  function discoverAgents(dir) {
    var found = [];
    var entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch (err) {
      return found;
    }
    for (var i = 0; i < entries.length; i++) {
      var entry = entries[i];
      if (!entry.name.endsWith('.md')) continue;
      if (!entry.isFile() && !entry.isSymbolicLink()) continue;
      var filePath = path.join(dir, entry.name);
      var content;
      try {
        content = fs.readFileSync(filePath, 'utf-8');
      } catch (err) {
        continue;
      }
      var parsed = parseFrontmatter(content);
      var fm = parsed.frontmatter;
      if (!fm.name || !fm.description) continue;
      var tools = fm.tools
        ? fm.tools.split(',').map(function (t) { return t.trim(); }).filter(function (t) { return t.length > 0; })
        : undefined;
      found.push({
        name: fm.name,
        description: fm.description,
        model: fm.model || undefined,
        tools: tools && tools.length > 0 ? tools : undefined,
        systemPrompt: parsed.body
      });
    }
    return found;
  }

  var agents = discoverAgents(agentsDir);
  // Zero agents discovered -> do not register the tool at all (no prompt pollution).
  if (agents.length === 0) return;

  function findAgent(name) {
    for (var i = 0; i < agents.length; i++) {
      if (agents[i].name === name) return agents[i];
    }
    return undefined;
  }

  function describeAgents() {
    return agents.map(function (a) { return a.name + ' \\u2014 ' + a.description; }).join('; ');
  }

  // ---- Self-invocation (ported from vendor/pi-cli/examples/extensions/subagent/index.ts's
  // getPiInvocation -- correctly targets the SAME pi binary currently running,
  // whether that's a bun-compiled standalone executable or an interpreted
  // script). DELIBERATE DIVERGENCE from the example: bun-compiled standalone
  // binaries report a VIRTUAL script path in process.argv[1] -- '/$bunfs/...'
  // on POSIX, but 'X:/~BUN/...' (either slash direction) on WINDOWS. PROBED
  // against the real vendored pi.exe (docs/protocol-pi/README.md's
  // probe-the-wire discipline): process.argv[1] === 'B:/~BUN/root/pi.exe',
  // and fs.existsSync() returns TRUE for that path because bun patches fs
  // for its virtual filesystem -- so the existsSync check alone cannot
  // filter it out. The example upstream only checks the POSIX '/$bunfs/'
  // form and would spawn \`pi.exe B:/~BUN/root/pi.exe --mode json ...\` on
  // Windows, landing the virtual path as a positional prompt arg; our port
  // detects both forms so the standalone-binary case correctly falls
  // through to the exec-name check below (pi.exe is not a generic runtime
  // -> {command: process.execPath}). ----
  function getPiInvocation(args) {
    var currentScript = process.argv[1];
    var isBunVirtualScript = !!currentScript && (
      currentScript.indexOf('/$bunfs/') === 0 ||
      /^[A-Za-z]:[\\\\/]~BUN[\\\\/]/.test(currentScript)
    );
    if (currentScript && !isBunVirtualScript && fs.existsSync(currentScript)) {
      return { command: process.execPath, args: [currentScript].concat(args) };
    }
    var execName = path.basename(process.execPath).toLowerCase();
    var isGenericRuntime = /^(node|bun)(\\.exe)?$/.test(execName);
    if (!isGenericRuntime) {
      return { command: process.execPath, args: args };
    }
    return { command: 'pi', args: args };
  }

  // ---- Temp prompt-file plumbing (ported writePromptToTempFile; no mutation
  // queue needed -- each call gets its own fresh mkdtemp dir, so there is no
  // cross-call collision to serialize against). ----
  function writePromptToTempFile(agentName, prompt) {
    var tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-subagent-'));
    var safeName = agentName.replace(/[^\\w.-]+/g, '_');
    var filePath = path.join(tmpDir, 'prompt-' + safeName + '.md');
    fs.writeFileSync(filePath, prompt, { encoding: 'utf-8', mode: 0o600 });
    return { dir: tmpDir, filePath: filePath };
  }

  function cleanupTempPrompt(tmp) {
    if (!tmp) return;
    try { fs.unlinkSync(tmp.filePath); } catch (err) { /* ignore */ }
    try { fs.rmdirSync(tmp.dir); } catch (err) { /* ignore */ }
  }

  // ---- Child process runner ----
  var SUBAGENT_TIMEOUT_MS = 10 * 60 * 1000; // 10 min per-child hang cap

  function killTree(proc) {
    // Windows: bash child processes spawned BY the subagent's own pi process
    // need tree-kill (same discipline as docs/protocol-pi/README.md "Behavior
    // gotchas" / OpencodeServerManager's identical taskkill usage) --
    // SIGTERM/SIGKILL alone would leave them orphaned.
    if (process.platform === 'win32' && proc.pid) {
      try {
        spawn('taskkill', ['/pid', String(proc.pid), '/T', '/F']);
      } catch (err) { /* ignore */ }
      return;
    }
    try { proc.kill('SIGTERM'); } catch (err) { /* ignore */ }
    setTimeout(function () {
      try { if (!proc.killed) proc.kill('SIGKILL'); } catch (err) { /* ignore */ }
    }, 5000);
  }

  // Recursion is structurally absent: NO -e flags are passed to the child, so
  // it loads no subagent tool, no approval bridge, no hosted tools --
  // regardless of which CLAUDEUI_PI_* env vars it inherits through the
  // default spawn env merge (none of them mean anything to a pi process with
  // zero extensions loaded). The child runs its agent-def toolset entirely
  // UNGATED -- see this file's header comment for the trust-model rationale.
  function runOneAgent(agentName, task, signal, onAgentUpdate) {
    return new Promise(function (resolve) {
      var agent = findAgent(agentName);
      var state = {
        agent: agentName,
        model: agent ? agent.model : undefined,
        status: 'running',
        messages: [],
        usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, cost: 0, turns: 0 }
      };

      if (!agent) {
        state.status = 'error';
        onAgentUpdate(state, []);
        resolve(state);
        return;
      }

      var args = ['--mode', 'json', '-p', '--no-session'];
      var model = agent.model || process.env.CLAUDEUI_PI_SUBAGENT_DEFAULT_MODEL;
      if (model) args.push('--model', model);
      if (agent.tools && agent.tools.length > 0) args.push('--tools', agent.tools.join(','));

      var tmpPrompt = null;
      if (agent.systemPrompt && agent.systemPrompt.trim()) {
        tmpPrompt = writePromptToTempFile(agent.name, agent.systemPrompt);
        args.push('--append-system-prompt', tmpPrompt.filePath);
      }
      args.push('Task: ' + task);

      var invocation = getPiInvocation(args);
      var proc = spawn(invocation.command, invocation.args, { shell: false, stdio: ['ignore', 'pipe', 'pipe'] });
      var buffer = '';
      var settled = false;
      var aborted = false;

      var timeoutHandle = setTimeout(function () {
        killTree(proc);
      }, SUBAGENT_TIMEOUT_MS);

      var abortHandler = function () {
        aborted = true;
        killTree(proc);
      };
      if (signal) {
        if (signal.aborted) abortHandler();
        else signal.addEventListener('abort', abortHandler, { once: true });
      }

      function processLine(line) {
        if (!line.trim()) return;
        var event;
        try {
          event = JSON.parse(line);
        } catch (err) {
          return;
        }
        if (event.type === 'message_end' && event.message) {
          var msg = event.message;
          state.messages.push(msg);
          if (msg.role === 'assistant') {
            state.usage.turns++;
            var usage = msg.usage;
            if (usage) {
              state.usage.input += usage.input || 0;
              state.usage.output += usage.output || 0;
              state.usage.cacheRead += usage.cacheRead || 0;
              state.usage.cacheWrite += usage.cacheWrite || 0;
              state.usage.cost += (usage.cost && usage.cost.total) || 0;
            }
            if (!state.model && msg.model) state.model = msg.model;
          }
          onAgentUpdate(state, [msg]);
        } else if (event.type === 'tool_result_end' && event.message) {
          state.messages.push(event.message);
          onAgentUpdate(state, [event.message]);
        }
      }

      proc.stdout.on('data', function (data) {
        buffer += data.toString();
        var lines = buffer.split('\\n');
        buffer = lines.pop() || '';
        for (var i = 0; i < lines.length; i++) processLine(lines[i]);
      });
      // stderr is swallowed here -- not surfaced to the model in v1 (a failed
      // child still reports through its exit code -> status:'error' below).
      proc.stderr.on('data', function () {});

      function finish(status) {
        if (settled) return;
        settled = true;
        clearTimeout(timeoutHandle);
        if (signal) signal.removeEventListener('abort', abortHandler);
        cleanupTempPrompt(tmpPrompt);
        state.status = status;
        onAgentUpdate(state, []);
        resolve(state);
      }

      proc.on('close', function (code) {
        if (buffer.trim()) processLine(buffer);
        finish(aborted ? 'error' : code === 0 ? 'done' : 'error');
      });

      proc.on('error', function () {
        finish('error');
      });
    });
  }

  function finalTextFor(state) {
    for (var i = state.messages.length - 1; i >= 0; i--) {
      var msg = state.messages[i];
      if (msg.role === 'assistant') {
        for (var j = 0; j < msg.content.length; j++) {
          if (msg.content[j].type === 'text') return msg.content[j].text;
        }
      }
    }
    return '';
  }

  function usageSummary(usage) {
    var parts = [];
    if (usage.turns) parts.push(usage.turns + ' turn' + (usage.turns > 1 ? 's' : ''));
    if (usage.cost) parts.push('$' + usage.cost.toFixed(4));
    return parts.join(' ');
  }

  pi.registerTool({
    name: 'subagent',
    label: 'Subagent',
    description:
      'Delegate a task to a specialized subagent running in its own isolated pi process. ' +
      'Single mode: {agent, task}. Parallel mode: {tasks: [{agent, task}, ...]}. ' +
      'Available agents: ' + describeAgents() + '.',
    parameters: {
      type: 'object',
      properties: {
        agent: { type: 'string', description: 'Name of the agent to invoke (single mode)' },
        task: { type: 'string', description: 'Task to delegate to the agent (single mode)' },
        tasks: {
          type: 'array',
          description: 'Array of {agent, task} pairs to run concurrently (parallel mode) -- provide EITHER agent+task OR tasks, not both',
          items: {
            type: 'object',
            properties: {
              agent: { type: 'string', description: 'Name of the agent to invoke' },
              task: { type: 'string', description: 'Task to delegate to the agent' }
            },
            required: ['agent', 'task']
          }
        }
      }
    },

    execute: async function (toolCallId, params, signal, onUpdate) {
      var hasTasks = Array.isArray(params.tasks) && params.tasks.length > 0;
      var hasSingle = !!(params.agent && params.task);
      if (hasTasks === hasSingle) {
        return {
          content: [{ type: 'text', text: 'Invalid parameters -- provide EITHER {agent, task} OR {tasks: [...]}, not both/neither. Available agents: ' + describeAgents() }],
          isError: true
        };
      }

      var requests = hasTasks ? params.tasks : [{ agent: params.agent, task: params.task }];

      // Stable index-order slots -- newMessages accumulates as a DELTA per
      // slot, flushed (reset to []) by every emitUpdate() call, so PiSession
      // never needs to dedupe what it already forwarded.
      var slots = requests.map(function (r) {
        return {
          agent: r.agent,
          model: undefined,
          status: 'running',
          usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, cost: 0, turns: 0 },
          pendingNew: []
        };
      });

      function emitUpdate() {
        if (!onUpdate) return;
        var text = slots.map(function (s) { return '[' + s.agent + '] ' + s.status; }).join('\\n');
        var agentsPayload = slots.map(function (s) {
          return { agent: s.agent, model: s.model, status: s.status, newMessages: s.pendingNew, usage: s.usage };
        });
        onUpdate({ content: [{ type: 'text', text: text }], details: { cuiSubagent: { v: 1, agents: agentsPayload } } });
        for (var i = 0; i < slots.length; i++) slots[i].pendingNew = [];
      }

      var results = await Promise.all(requests.map(function (r, index) {
        return runOneAgent(r.agent, r.task, signal, function (state, newMsgs) {
          slots[index].model = state.model;
          slots[index].status = state.status;
          slots[index].usage = state.usage;
          slots[index].pendingNew = slots[index].pendingNew.concat(newMsgs);
          emitUpdate();
        });
      }));

      var successCount = 0;
      var summaries = results.map(function (r) {
        if (r.status === 'done') successCount++;
        var text = finalTextFor(r) || '(no output)';
        var usage = usageSummary(r.usage);
        return '### [' + r.agent + '] ' + r.status + (usage ? ' (' + usage + ')' : '') + '\\n\\n' + text;
      });

      var finalAgents = slots.map(function (s, index) {
        return { agent: s.agent, model: results[index].model, status: results[index].status, newMessages: [], usage: results[index].usage };
      });

      return {
        content: [{ type: 'text', text: summaries.join('\\n\\n---\\n\\n') }],
        details: { cuiSubagent: { v: 1, agents: finalAgents } },
        isError: successCount === 0
      };
    }
  });
}
`
