// Generated by scripts/generate-codex-protocol.mjs — do not edit by hand.
// Source: openai/codex codex-rs/app-server-protocol at 3ac9870e21f4ce9a28c3ae3b878b7f8f95eff06d
// Regenerate: bun run generate-codex-protocol (when bumping codexCliVersion)


import type * as S from './schema';

export const CLIENT_REQUEST_METHODS = {
  "initialize": "initialize",
  "thread/start": "thread/start",
  "thread/resume": "thread/resume",
  "thread/fork": "thread/fork",
  "thread/archive": "thread/archive",
  "thread/delete": "thread/delete",
  "thread/unsubscribe": "thread/unsubscribe",
  "thread/name/set": "thread/name/set",
  "thread/goal/set": "thread/goal/set",
  "thread/goal/get": "thread/goal/get",
  "thread/goal/clear": "thread/goal/clear",
  "thread/metadata/update": "thread/metadata/update",
  "thread/unarchive": "thread/unarchive",
  "thread/compact/start": "thread/compact/start",
  "thread/shellCommand": "thread/shellCommand",
  "thread/approveGuardianDeniedAction": "thread/approveGuardianDeniedAction",
  "thread/rollback": "thread/rollback",
  "thread/list": "thread/list",
  "thread/loaded/list": "thread/loaded/list",
  "thread/read": "thread/read",
  "thread/inject_items": "thread/inject_items",
  "skills/list": "skills/list",
  "skills/extraRoots/set": "skills/extraRoots/set",
  "hooks/list": "hooks/list",
  "marketplace/add": "marketplace/add",
  "marketplace/remove": "marketplace/remove",
  "marketplace/upgrade": "marketplace/upgrade",
  "plugin/list": "plugin/list",
  "plugin/installed": "plugin/installed",
  "plugin/read": "plugin/read",
  "plugin/skill/read": "plugin/skill/read",
  "plugin/share/save": "plugin/share/save",
  "plugin/share/updateTargets": "plugin/share/updateTargets",
  "plugin/share/list": "plugin/share/list",
  "plugin/share/checkout": "plugin/share/checkout",
  "plugin/share/delete": "plugin/share/delete",
  "app/list": "app/list",
  "fs/readFile": "fs/readFile",
  "fs/writeFile": "fs/writeFile",
  "fs/createDirectory": "fs/createDirectory",
  "fs/getMetadata": "fs/getMetadata",
  "fs/readDirectory": "fs/readDirectory",
  "fs/remove": "fs/remove",
  "fs/copy": "fs/copy",
  "fs/watch": "fs/watch",
  "fs/unwatch": "fs/unwatch",
  "skills/config/write": "skills/config/write",
  "plugin/install": "plugin/install",
  "plugin/uninstall": "plugin/uninstall",
  "turn/start": "turn/start",
  "turn/steer": "turn/steer",
  "turn/interrupt": "turn/interrupt",
  "review/start": "review/start",
  "model/list": "model/list",
  "modelProvider/capabilities/read": "modelProvider/capabilities/read",
  "experimentalFeature/list": "experimentalFeature/list",
  "permissionProfile/list": "permissionProfile/list",
  "experimentalFeature/enablement/set": "experimentalFeature/enablement/set",
  "mcpServer/oauth/login": "mcpServer/oauth/login",
  "config/mcpServer/reload": "config/mcpServer/reload",
  "mcpServerStatus/list": "mcpServerStatus/list",
  "mcpServer/resource/read": "mcpServer/resource/read",
  "mcpServer/tool/call": "mcpServer/tool/call",
  "windowsSandbox/setupStart": "windowsSandbox/setupStart",
  "windowsSandbox/readiness": "windowsSandbox/readiness",
  "account/login/start": "account/login/start",
  "account/login/cancel": "account/login/cancel",
  "account/logout": "account/logout",
  "account/rateLimits/read": "account/rateLimits/read",
  "account/usage/read": "account/usage/read",
  "account/sendAddCreditsNudgeEmail": "account/sendAddCreditsNudgeEmail",
  "feedback/upload": "feedback/upload",
  "command/exec": "command/exec",
  "command/exec/write": "command/exec/write",
  "command/exec/terminate": "command/exec/terminate",
  "command/exec/resize": "command/exec/resize",
  "config/read": "config/read",
  "externalAgentConfig/detect": "externalAgentConfig/detect",
  "externalAgentConfig/import": "externalAgentConfig/import",
  "config/value/write": "config/value/write",
  "config/batchWrite": "config/batchWrite",
  "configRequirements/read": "configRequirements/read",
  "account/read": "account/read",
  "fuzzyFileSearch": "fuzzyFileSearch",
} as const;

export const CLIENT_NOTIFICATION_METHODS = {
  "initialized": "initialized",
} as const;

export const SERVER_REQUEST_METHODS = {
  "item/commandExecution/requestApproval": "item/commandExecution/requestApproval",
  "item/fileChange/requestApproval": "item/fileChange/requestApproval",
  "item/tool/requestUserInput": "item/tool/requestUserInput",
  "mcpServer/elicitation/request": "mcpServer/elicitation/request",
  "item/permissions/requestApproval": "item/permissions/requestApproval",
  "item/tool/call": "item/tool/call",
  "account/chatgptAuthTokens/refresh": "account/chatgptAuthTokens/refresh",
  "attestation/generate": "attestation/generate",
  "applyPatchApproval": "applyPatchApproval",
  "execCommandApproval": "execCommandApproval",
} as const;

export const SERVER_NOTIFICATION_METHODS = {
  "error": "error",
  "thread/started": "thread/started",
  "thread/status/changed": "thread/status/changed",
  "thread/archived": "thread/archived",
  "thread/deleted": "thread/deleted",
  "thread/unarchived": "thread/unarchived",
  "thread/closed": "thread/closed",
  "skills/changed": "skills/changed",
  "thread/name/updated": "thread/name/updated",
  "thread/goal/updated": "thread/goal/updated",
  "thread/goal/cleared": "thread/goal/cleared",
  "thread/settings/updated": "thread/settings/updated",
  "thread/tokenUsage/updated": "thread/tokenUsage/updated",
  "turn/started": "turn/started",
  "hook/started": "hook/started",
  "turn/completed": "turn/completed",
  "hook/completed": "hook/completed",
  "turn/diff/updated": "turn/diff/updated",
  "turn/plan/updated": "turn/plan/updated",
  "item/started": "item/started",
  "item/autoApprovalReview/started": "item/autoApprovalReview/started",
  "item/autoApprovalReview/completed": "item/autoApprovalReview/completed",
  "item/completed": "item/completed",
  "item/agentMessage/delta": "item/agentMessage/delta",
  "item/plan/delta": "item/plan/delta",
  "command/exec/outputDelta": "command/exec/outputDelta",
  "process/outputDelta": "process/outputDelta",
  "process/exited": "process/exited",
  "item/commandExecution/outputDelta": "item/commandExecution/outputDelta",
  "item/commandExecution/terminalInteraction": "item/commandExecution/terminalInteraction",
  "item/fileChange/outputDelta": "item/fileChange/outputDelta",
  "item/fileChange/patchUpdated": "item/fileChange/patchUpdated",
  "serverRequest/resolved": "serverRequest/resolved",
  "item/mcpToolCall/progress": "item/mcpToolCall/progress",
  "mcpServer/oauthLogin/completed": "mcpServer/oauthLogin/completed",
  "mcpServer/startupStatus/updated": "mcpServer/startupStatus/updated",
  "account/updated": "account/updated",
  "account/rateLimits/updated": "account/rateLimits/updated",
  "app/list/updated": "app/list/updated",
  "remoteControl/status/changed": "remoteControl/status/changed",
  "externalAgentConfig/import/completed": "externalAgentConfig/import/completed",
  "fs/changed": "fs/changed",
  "item/reasoning/summaryTextDelta": "item/reasoning/summaryTextDelta",
  "item/reasoning/summaryPartAdded": "item/reasoning/summaryPartAdded",
  "item/reasoning/textDelta": "item/reasoning/textDelta",
  "thread/compacted": "thread/compacted",
  "model/rerouted": "model/rerouted",
  "model/verification": "model/verification",
  "turn/moderationMetadata": "turn/moderationMetadata",
  "warning": "warning",
  "guardianWarning": "guardianWarning",
  "deprecationNotice": "deprecationNotice",
  "configWarning": "configWarning",
  "fuzzyFileSearch/sessionUpdated": "fuzzyFileSearch/sessionUpdated",
  "fuzzyFileSearch/sessionCompleted": "fuzzyFileSearch/sessionCompleted",
  "thread/realtime/started": "thread/realtime/started",
  "thread/realtime/itemAdded": "thread/realtime/itemAdded",
  "thread/realtime/transcript/delta": "thread/realtime/transcript/delta",
  "thread/realtime/transcript/done": "thread/realtime/transcript/done",
  "thread/realtime/outputAudio/delta": "thread/realtime/outputAudio/delta",
  "thread/realtime/sdp": "thread/realtime/sdp",
  "thread/realtime/error": "thread/realtime/error",
  "thread/realtime/closed": "thread/realtime/closed",
  "windows/worldWritableWarning": "windows/worldWritableWarning",
  "windowsSandbox/setupCompleted": "windowsSandbox/setupCompleted",
  "account/login/completed": "account/login/completed",
} as const;

export type ClientRequestMethod = keyof typeof CLIENT_REQUEST_METHODS;
export type ClientNotificationMethod = keyof typeof CLIENT_NOTIFICATION_METHODS;
export type ServerRequestMethod = keyof typeof SERVER_REQUEST_METHODS;
export type ServerNotificationMethod = keyof typeof SERVER_NOTIFICATION_METHODS;

export interface ClientRequestParamsByMethod {
  readonly "initialize": S.V1InitializeParams;
  readonly "thread/start": S.V2ThreadStartParams;
  readonly "thread/resume": S.V2ThreadResumeParams;
  readonly "thread/fork": S.V2ThreadForkParams;
  readonly "thread/archive": S.V2ThreadArchiveParams;
  readonly "thread/delete": S.V2ThreadDeleteParams;
  readonly "thread/unsubscribe": S.V2ThreadUnsubscribeParams;
  readonly "thread/name/set": S.V2ThreadSetNameParams;
  readonly "thread/goal/set": S.V2ThreadGoalSetParams;
  readonly "thread/goal/get": S.V2ThreadGoalGetParams;
  readonly "thread/goal/clear": S.V2ThreadGoalClearParams;
  readonly "thread/metadata/update": S.V2ThreadMetadataUpdateParams;
  readonly "thread/unarchive": S.V2ThreadUnarchiveParams;
  readonly "thread/compact/start": S.V2ThreadCompactStartParams;
  readonly "thread/shellCommand": S.V2ThreadShellCommandParams;
  readonly "thread/approveGuardianDeniedAction": S.V2ThreadApproveGuardianDeniedActionParams;
  readonly "thread/rollback": S.V2ThreadRollbackParams;
  readonly "thread/list": S.V2ThreadListParams;
  readonly "thread/loaded/list": S.V2ThreadLoadedListParams;
  readonly "thread/read": S.V2ThreadReadParams;
  readonly "thread/inject_items": S.V2ThreadInjectItemsParams;
  readonly "skills/list": S.V2SkillsListParams;
  readonly "skills/extraRoots/set": S.V2SkillsExtraRootsSetParams;
  readonly "hooks/list": S.V2HooksListParams;
  readonly "marketplace/add": S.V2MarketplaceAddParams;
  readonly "marketplace/remove": S.V2MarketplaceRemoveParams;
  readonly "marketplace/upgrade": S.V2MarketplaceUpgradeParams;
  readonly "plugin/list": S.V2PluginListParams;
  readonly "plugin/installed": S.V2PluginInstalledParams;
  readonly "plugin/read": S.V2PluginReadParams;
  readonly "plugin/skill/read": S.V2PluginSkillReadParams;
  readonly "plugin/share/save": S.V2PluginShareSaveParams;
  readonly "plugin/share/updateTargets": S.V2PluginShareUpdateTargetsParams;
  readonly "plugin/share/list": S.V2PluginShareListParams;
  readonly "plugin/share/checkout": S.V2PluginShareCheckoutParams;
  readonly "plugin/share/delete": S.V2PluginShareDeleteParams;
  readonly "app/list": S.V2AppsListParams;
  readonly "fs/readFile": S.V2FsReadFileParams;
  readonly "fs/writeFile": S.V2FsWriteFileParams;
  readonly "fs/createDirectory": S.V2FsCreateDirectoryParams;
  readonly "fs/getMetadata": S.V2FsGetMetadataParams;
  readonly "fs/readDirectory": S.V2FsReadDirectoryParams;
  readonly "fs/remove": S.V2FsRemoveParams;
  readonly "fs/copy": S.V2FsCopyParams;
  readonly "fs/watch": S.V2FsWatchParams;
  readonly "fs/unwatch": S.V2FsUnwatchParams;
  readonly "skills/config/write": S.V2SkillsConfigWriteParams;
  readonly "plugin/install": S.V2PluginInstallParams;
  readonly "plugin/uninstall": S.V2PluginUninstallParams;
  readonly "turn/start": S.V2TurnStartParams;
  readonly "turn/steer": S.V2TurnSteerParams;
  readonly "turn/interrupt": S.V2TurnInterruptParams;
  readonly "review/start": S.V2ReviewStartParams;
  readonly "model/list": S.V2ModelListParams;
  readonly "modelProvider/capabilities/read": S.V2ModelProviderCapabilitiesReadParams;
  readonly "experimentalFeature/list": S.V2ExperimentalFeatureListParams;
  readonly "permissionProfile/list": S.V2PermissionProfileListParams;
  readonly "experimentalFeature/enablement/set": S.V2ExperimentalFeatureEnablementSetParams;
  readonly "mcpServer/oauth/login": S.V2McpServerOauthLoginParams;
  readonly "config/mcpServer/reload": null;
  readonly "mcpServerStatus/list": S.V2ListMcpServerStatusParams;
  readonly "mcpServer/resource/read": S.V2McpResourceReadParams;
  readonly "mcpServer/tool/call": S.V2McpServerToolCallParams;
  readonly "windowsSandbox/setupStart": S.V2WindowsSandboxSetupStartParams;
  readonly "windowsSandbox/readiness": null;
  readonly "account/login/start": S.V2LoginAccountParams;
  readonly "account/login/cancel": S.V2CancelLoginAccountParams;
  readonly "account/logout": null;
  readonly "account/rateLimits/read": null;
  readonly "account/usage/read": null;
  readonly "account/sendAddCreditsNudgeEmail": S.V2SendAddCreditsNudgeEmailParams;
  readonly "feedback/upload": S.V2FeedbackUploadParams;
  readonly "command/exec": S.V2CommandExecParams;
  readonly "command/exec/write": S.V2CommandExecWriteParams;
  readonly "command/exec/terminate": S.V2CommandExecTerminateParams;
  readonly "command/exec/resize": S.V2CommandExecResizeParams;
  readonly "config/read": S.V2ConfigReadParams;
  readonly "externalAgentConfig/detect": S.V2ExternalAgentConfigDetectParams;
  readonly "externalAgentConfig/import": S.V2ExternalAgentConfigImportParams;
  readonly "config/value/write": S.V2ConfigValueWriteParams;
  readonly "config/batchWrite": S.V2ConfigBatchWriteParams;
  readonly "configRequirements/read": null;
  readonly "account/read": S.V2GetAccountParams;
  readonly "fuzzyFileSearch": S.FuzzyFileSearchParams;
}

export interface ClientRequestResponsesByMethod {
  readonly "initialize": S.V1InitializeResponse;
  readonly "thread/start": S.V2ThreadStartResponse;
  readonly "thread/resume": S.V2ThreadResumeResponse;
  readonly "thread/fork": S.V2ThreadForkResponse;
  readonly "thread/archive": S.V2ThreadArchiveResponse;
  readonly "thread/delete": S.V2ThreadDeleteResponse;
  readonly "thread/unsubscribe": S.V2ThreadUnsubscribeResponse;
  readonly "thread/name/set": S.V2ThreadSetNameResponse;
  readonly "thread/goal/set": S.V2ThreadGoalSetResponse;
  readonly "thread/goal/get": S.V2ThreadGoalGetResponse;
  readonly "thread/goal/clear": S.V2ThreadGoalClearResponse;
  readonly "thread/metadata/update": S.V2ThreadMetadataUpdateResponse;
  readonly "thread/unarchive": S.V2ThreadUnarchiveResponse;
  readonly "thread/compact/start": S.V2ThreadCompactStartResponse;
  readonly "thread/shellCommand": S.V2ThreadShellCommandResponse;
  readonly "thread/approveGuardianDeniedAction": S.V2ThreadApproveGuardianDeniedActionResponse;
  readonly "thread/rollback": S.V2ThreadRollbackResponse;
  readonly "thread/list": S.V2ThreadListResponse;
  readonly "thread/loaded/list": S.V2ThreadLoadedListResponse;
  readonly "thread/read": S.V2ThreadReadResponse;
  readonly "thread/inject_items": S.V2ThreadInjectItemsResponse;
  readonly "skills/list": S.V2SkillsListResponse;
  readonly "skills/extraRoots/set": S.V2SkillsExtraRootsSetResponse;
  readonly "hooks/list": S.V2HooksListResponse;
  readonly "marketplace/add": S.V2MarketplaceAddResponse;
  readonly "marketplace/remove": S.V2MarketplaceRemoveResponse;
  readonly "marketplace/upgrade": S.V2MarketplaceUpgradeResponse;
  readonly "plugin/list": S.V2PluginListResponse;
  readonly "plugin/installed": S.V2PluginInstalledResponse;
  readonly "plugin/read": S.V2PluginReadResponse;
  readonly "plugin/skill/read": S.V2PluginSkillReadResponse;
  readonly "plugin/share/save": S.V2PluginShareSaveResponse;
  readonly "plugin/share/updateTargets": S.V2PluginShareUpdateTargetsResponse;
  readonly "plugin/share/list": S.V2PluginShareListResponse;
  readonly "plugin/share/checkout": S.V2PluginShareCheckoutResponse;
  readonly "plugin/share/delete": S.V2PluginShareDeleteResponse;
  readonly "app/list": S.V2AppsListResponse;
  readonly "fs/readFile": S.V2FsReadFileResponse;
  readonly "fs/writeFile": S.V2FsWriteFileResponse;
  readonly "fs/createDirectory": S.V2FsCreateDirectoryResponse;
  readonly "fs/getMetadata": S.V2FsGetMetadataResponse;
  readonly "fs/readDirectory": S.V2FsReadDirectoryResponse;
  readonly "fs/remove": S.V2FsRemoveResponse;
  readonly "fs/copy": S.V2FsCopyResponse;
  readonly "fs/watch": S.V2FsWatchResponse;
  readonly "fs/unwatch": S.V2FsUnwatchResponse;
  readonly "skills/config/write": S.V2SkillsConfigWriteResponse;
  readonly "plugin/install": S.V2PluginInstallResponse;
  readonly "plugin/uninstall": S.V2PluginUninstallResponse;
  readonly "turn/start": S.V2TurnStartResponse;
  readonly "turn/steer": S.V2TurnSteerResponse;
  readonly "turn/interrupt": S.V2TurnInterruptResponse;
  readonly "review/start": S.V2ReviewStartResponse;
  readonly "model/list": S.V2ModelListResponse;
  readonly "modelProvider/capabilities/read": S.V2ModelProviderCapabilitiesReadResponse;
  readonly "experimentalFeature/list": S.V2ExperimentalFeatureListResponse;
  readonly "permissionProfile/list": S.V2PermissionProfileListResponse;
  readonly "experimentalFeature/enablement/set": S.V2ExperimentalFeatureEnablementSetResponse;
  readonly "mcpServer/oauth/login": S.V2McpServerOauthLoginResponse;
  readonly "config/mcpServer/reload": S.V2McpServerRefreshResponse;
  readonly "mcpServerStatus/list": S.V2ListMcpServerStatusResponse;
  readonly "mcpServer/resource/read": S.V2McpResourceReadResponse;
  readonly "mcpServer/tool/call": S.V2McpServerToolCallResponse;
  readonly "windowsSandbox/setupStart": S.V2WindowsSandboxSetupStartResponse;
  readonly "windowsSandbox/readiness": S.V2WindowsSandboxReadinessResponse;
  readonly "account/login/start": S.V2LoginAccountResponse;
  readonly "account/login/cancel": S.V2CancelLoginAccountResponse;
  readonly "account/logout": S.V2LogoutAccountResponse;
  readonly "account/rateLimits/read": S.V2GetAccountRateLimitsResponse;
  readonly "account/usage/read": S.V2GetAccountTokenUsageResponse;
  readonly "account/sendAddCreditsNudgeEmail": S.V2SendAddCreditsNudgeEmailResponse;
  readonly "feedback/upload": S.V2FeedbackUploadResponse;
  readonly "command/exec": S.V2CommandExecResponse;
  readonly "command/exec/write": S.V2CommandExecWriteResponse;
  readonly "command/exec/terminate": S.V2CommandExecTerminateResponse;
  readonly "command/exec/resize": S.V2CommandExecResizeResponse;
  readonly "config/read": S.V2ConfigReadResponse;
  readonly "externalAgentConfig/detect": S.V2ExternalAgentConfigDetectResponse;
  readonly "externalAgentConfig/import": S.V2ExternalAgentConfigImportResponse;
  readonly "config/value/write": S.V2ConfigWriteResponse;
  readonly "config/batchWrite": S.V2ConfigWriteResponse;
  readonly "configRequirements/read": S.V2ConfigRequirementsReadResponse;
  readonly "account/read": S.V2GetAccountResponse;
  readonly "fuzzyFileSearch": S.FuzzyFileSearchResponse;
}

export interface ClientNotificationParamsByMethod {
  readonly "initialized": undefined;
}

export interface ServerRequestParamsByMethod {
  readonly "item/commandExecution/requestApproval": S.CommandExecutionRequestApprovalParams;
  readonly "item/fileChange/requestApproval": S.FileChangeRequestApprovalParams;
  readonly "item/tool/requestUserInput": S.ToolRequestUserInputParams;
  readonly "mcpServer/elicitation/request": S.McpServerElicitationRequestParams;
  readonly "item/permissions/requestApproval": S.PermissionsRequestApprovalParams;
  readonly "item/tool/call": S.DynamicToolCallParams;
  readonly "account/chatgptAuthTokens/refresh": S.ChatgptAuthTokensRefreshParams;
  readonly "attestation/generate": S.AttestationGenerateParams;
  readonly "applyPatchApproval": S.ApplyPatchApprovalParams;
  readonly "execCommandApproval": S.ExecCommandApprovalParams;
}

export interface ServerRequestResponsesByMethod {
  readonly "item/commandExecution/requestApproval": S.CommandExecutionRequestApprovalResponse;
  readonly "item/fileChange/requestApproval": S.FileChangeRequestApprovalResponse;
  readonly "item/tool/requestUserInput": S.ToolRequestUserInputResponse;
  readonly "mcpServer/elicitation/request": S.McpServerElicitationRequestResponse;
  readonly "item/permissions/requestApproval": S.PermissionsRequestApprovalResponse;
  readonly "item/tool/call": S.DynamicToolCallResponse;
  readonly "account/chatgptAuthTokens/refresh": S.ChatgptAuthTokensRefreshResponse;
  readonly "attestation/generate": S.AttestationGenerateResponse;
  readonly "applyPatchApproval": S.ApplyPatchApprovalResponse;
  readonly "execCommandApproval": S.ExecCommandApprovalResponse;
}

export interface ServerNotificationParamsByMethod {
  readonly "error": S.V2ErrorNotification;
  readonly "thread/started": S.V2ThreadStartedNotification;
  readonly "thread/status/changed": S.V2ThreadStatusChangedNotification;
  readonly "thread/archived": S.V2ThreadArchivedNotification;
  readonly "thread/deleted": S.V2ThreadDeletedNotification;
  readonly "thread/unarchived": S.V2ThreadUnarchivedNotification;
  readonly "thread/closed": S.V2ThreadClosedNotification;
  readonly "skills/changed": S.V2SkillsChangedNotification;
  readonly "thread/name/updated": S.V2ThreadNameUpdatedNotification;
  readonly "thread/goal/updated": S.V2ThreadGoalUpdatedNotification;
  readonly "thread/goal/cleared": S.V2ThreadGoalClearedNotification;
  readonly "thread/settings/updated": S.V2ThreadSettingsUpdatedNotification;
  readonly "thread/tokenUsage/updated": S.V2ThreadTokenUsageUpdatedNotification;
  readonly "turn/started": S.V2TurnStartedNotification;
  readonly "hook/started": S.V2HookStartedNotification;
  readonly "turn/completed": S.V2TurnCompletedNotification;
  readonly "hook/completed": S.V2HookCompletedNotification;
  readonly "turn/diff/updated": S.V2TurnDiffUpdatedNotification;
  readonly "turn/plan/updated": S.V2TurnPlanUpdatedNotification;
  readonly "item/started": S.V2ItemStartedNotification;
  readonly "item/autoApprovalReview/started": S.V2ItemGuardianApprovalReviewStartedNotification;
  readonly "item/autoApprovalReview/completed": S.V2ItemGuardianApprovalReviewCompletedNotification;
  readonly "item/completed": S.V2ItemCompletedNotification;
  readonly "item/agentMessage/delta": S.V2AgentMessageDeltaNotification;
  readonly "item/plan/delta": S.V2PlanDeltaNotification;
  readonly "command/exec/outputDelta": S.V2CommandExecOutputDeltaNotification;
  readonly "process/outputDelta": S.V2ProcessOutputDeltaNotification;
  readonly "process/exited": S.V2ProcessExitedNotification;
  readonly "item/commandExecution/outputDelta": S.V2CommandExecutionOutputDeltaNotification;
  readonly "item/commandExecution/terminalInteraction": S.V2TerminalInteractionNotification;
  readonly "item/fileChange/outputDelta": S.V2FileChangeOutputDeltaNotification;
  readonly "item/fileChange/patchUpdated": S.V2FileChangePatchUpdatedNotification;
  readonly "serverRequest/resolved": S.V2ServerRequestResolvedNotification;
  readonly "item/mcpToolCall/progress": S.V2McpToolCallProgressNotification;
  readonly "mcpServer/oauthLogin/completed": S.V2McpServerOauthLoginCompletedNotification;
  readonly "mcpServer/startupStatus/updated": S.V2McpServerStatusUpdatedNotification;
  readonly "account/updated": S.V2AccountUpdatedNotification;
  readonly "account/rateLimits/updated": S.V2AccountRateLimitsUpdatedNotification;
  readonly "app/list/updated": S.V2AppListUpdatedNotification;
  readonly "remoteControl/status/changed": S.V2RemoteControlStatusChangedNotification;
  readonly "externalAgentConfig/import/completed": S.V2ExternalAgentConfigImportCompletedNotification;
  readonly "fs/changed": S.V2FsChangedNotification;
  readonly "item/reasoning/summaryTextDelta": S.V2ReasoningSummaryTextDeltaNotification;
  readonly "item/reasoning/summaryPartAdded": S.V2ReasoningSummaryPartAddedNotification;
  readonly "item/reasoning/textDelta": S.V2ReasoningTextDeltaNotification;
  readonly "thread/compacted": S.V2ContextCompactedNotification;
  readonly "model/rerouted": S.V2ModelReroutedNotification;
  readonly "model/verification": S.V2ModelVerificationNotification;
  readonly "turn/moderationMetadata": S.V2TurnModerationMetadataNotification;
  readonly "warning": S.V2WarningNotification;
  readonly "guardianWarning": S.V2GuardianWarningNotification;
  readonly "deprecationNotice": S.V2DeprecationNoticeNotification;
  readonly "configWarning": S.V2ConfigWarningNotification;
  readonly "fuzzyFileSearch/sessionUpdated": S.FuzzyFileSearchSessionUpdatedNotification;
  readonly "fuzzyFileSearch/sessionCompleted": S.FuzzyFileSearchSessionCompletedNotification;
  readonly "thread/realtime/started": S.V2ThreadRealtimeStartedNotification;
  readonly "thread/realtime/itemAdded": S.V2ThreadRealtimeItemAddedNotification;
  readonly "thread/realtime/transcript/delta": S.V2ThreadRealtimeTranscriptDeltaNotification;
  readonly "thread/realtime/transcript/done": S.V2ThreadRealtimeTranscriptDoneNotification;
  readonly "thread/realtime/outputAudio/delta": S.V2ThreadRealtimeOutputAudioDeltaNotification;
  readonly "thread/realtime/sdp": S.V2ThreadRealtimeSdpNotification;
  readonly "thread/realtime/error": S.V2ThreadRealtimeErrorNotification;
  readonly "thread/realtime/closed": S.V2ThreadRealtimeClosedNotification;
  readonly "windows/worldWritableWarning": S.V2WindowsWorldWritableWarningNotification;
  readonly "windowsSandbox/setupCompleted": S.V2WindowsSandboxSetupCompletedNotification;
  readonly "account/login/completed": S.V2AccountLoginCompletedNotification;
}
